const ADD_ACTIVE_TEAM;
const ADD_ACTIVE_PM;
const REMOVE_ACTIVE_TEAM;
const REMOVE_ACTIVE_PM;
const SET_PROJECT_FILTER;
const SET_PROJECT_SEARCHTERM;
const SET_PROJECT_SORT;
const SET_ACTIVE_PROJECT;
